# Generated by Django 5.2.7 on 2026-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_invoice_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("vehicle_received", "Vehicle Received"),
                    ("inspection_done", "Inspection Completed (Pending Approval)"),
                    ("estimate_approved", "Estimate Approved"),
                    ("estimate_rejected", "Estimate Rejected"),
                    ("in_progress", "Service In Progress"),
                    ("completed", "Service Completed"),
                    ("ready_pickup", "Ready for Pickup"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatusupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("vehicle_received", "Vehicle Received"),
                    ("inspection_done", "Inspection Completed (Pending Approval)"),
                    ("estimate_approved", "Estimate Approved"),
                    ("estimate_rejected", "Estimate Rejected"),
                    ("in_progress", "Service In Progress"),
                    ("completed", "Service Completed"),
                    ("ready_pickup", "Ready for Pickup"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
