# Generated by Django 5.2.7 on 2026-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="estimate_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Detailed items for the cost estimate",
            ),
        ),
    ]
